language: python
dist: bionic

cache: pip

python:
  - "3.7"

addons:
  apt:
    packages:
      - python3-tk

branches:
  only:
    - master

install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -e .

script:
  - ./runflake8
  - ./runisort
  - coverage run --source=iris_dataset_classifier iris_dataset_classifier/tests/test_classifier.py

after_success:
  coveralls
